template: CoffeeMaker

logging:
  level: INFO
  loggers:
    CoffeeMaker: DEBUG

server:
  rootPath: /api/
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081
